version: '3.8'

services:
  zonos-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./uploaded_audio:/app/uploaded_audio
    environment:
      - USE_GPU=true
      - PYTHONPATH=/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]